
module.exports = async (client, interaction, args) => {

    const user = interaction.options.getUser('user');

    var roasts = [
        "*Vous met au four.*",
        "Vous êtes tellement stupide.",
        "Désolé, je ne t'entends pas à cause de ton ennui.",
        "J'ai mieux à faire.",
        "Tu es aussi stupide que Cleverbot.",
        "Votre QI est inférieur à celui de la fosse des Mariannes.",
        "Tu es tellement ennuyeux que même les mouches restent à l'écart de ta puanteur.",
        "Va-t-en s'il te plaît.",
        "Je te jetterais un regard méchant mais tu en as déjà un.",
        "On dirait que ton visage a pris feu et que quelqu'un a essayé de l'éteindre avec un marteau.",
        "Votre arbre généalogique doit être un cactus parce que tout le monde dessus est un connard.",
        "Un jour tu iras loin, et j'espère que tu y resteras.",
        "Le zoo a appelé. Ils se demandent comment tu es sorti de ta cage.",
        "J'espérais une bataille d'intelligence, mais vous ne semblez pas armé.",
        "Vous êtes la preuve que l'évolution peut s'inverser.",
        "Les cerveaux ne sont pas tout, dans votre cas, ils ne sont rien.",
        "Désolé, je n'ai pas compris, je ne parle pas idiot.",
        "Pourquoi est-il acceptable que tu sois un idiot, mais pas que je le souligne ?",
        "Nous sommes tous issus du singe, mais vous n'êtes pas allé assez loin.",
        "Même les singes peuvent aller dans l'espace, donc il vous manque clairement un certain potentiel.",
        "C'est l'intelligence qui prime sur les muscles, et pourtant vous n'avez ni l'un ni l'autre.",
        "Tu ressembles à un singe et tu en sens un aussi.",
        "Même parmi les idiots tu manques.",
        "Vous échouez même si vous ne faites absolument rien.",
        "S'il y avait un vote pour le moins susceptible de réussir, vous remporteriez le premier prix.",
        "Je suis entouré d'idiots... Ou attends, c'est juste toi.",
        "Je veux rentrer à la maison. Eh bien, vraiment, je veux juste m'éloigner de l'horrible arôme que tu dégages là-bas.",
        "Chaque fois que tu me touches, je dois rentrer chez moi et laver tous mes vêtements neuf fois juste pour retrouver une odeur normale.",
        "Si j'avais un dollar pour chaque cerveau que vous n'avez pas, j'en aurais un.",
        "Je t'aiderais à réussir mais tu en es incapable.",
        "La racine de vos cheveux est construite comme un graphique, les forces positives et négatives s'attirent mais la tondeuse et vos cheveux se repoussent.",
        "Je connais une bonne blague ! Toi !",
        "Vous avez deux parties de votre cerveau, la gauche et la droite. Du côté gauche, il n'y a plus rien de bien. Du côté droit, il ne reste plus rien.",
        "Est-ce que ton cul est jaloux de la quantité de merde qui vient de sortir de ta bouche ?",
        "Je ne m'engage pas dans un combat mental avec des personnes non armées.",
        "Deux torts ne font pas un bien, prends tes parents comme exemple.",
        "Votre acte de naissance est une lettre d'excuses de l'usine de préservatifs.",
        "Vous avez l'air raisonnable. Il doit être temps d'augmenter mes médicaments !",
        "Vous devez être né sur une autoroute car c'est là que se produisent la plupart des accidents.",
        "Tu es tellement moche que quand ta mère t'a déposé à l'école, elle a reçu une amende pour détritus.",
        "Si le rire est le meilleur remède, votre visage doit guérir le monde.",
        "J'aimerais voir les choses de votre point de vue mais je n'arrive pas à mettre ma tête aussi loin dans mon cul.",
        "La seule façon de baiser, c'est de ramper dans le cul d'une poule et d'attendre.",
        "Je suis jaloux de tous les gens qui ne t'ont pas rencontré !",
        "Si j'avais un visage comme le tien, je poursuivrais mes parents en justice.",
        "Il n'y a qu'un seul problème avec ton visage. Je peux le voir.",
        "Tu n'aimes pas la nature, malgré ce qu'elle t'a fait ?",
        "Quelle langue parles-tu ? Parce que ça ressemble à des conneries.",
        "La stupidité n'est pas un crime donc vous êtes libre de partir.",
        "Alors, une pensée vous a traversé l'esprit ? Cela a dû être un voyage long et solitaire.",
        "Vous avez un QI à température ambiante - si la pièce est en Antarctique.",
        "Si tu veux vraiment connaître les erreurs, tu devrais demander à tes parents.",
        "Je te demanderais quel âge tu as mais je sais que tu ne peux pas compter aussi haut.",
        "Voulez-vous savoir comment je reçois toutes ces insultes ? J'utilise quelque chose qui s'appelle l'intelligence.",
        "J'allais te lancer un regard méchant, mais tu en as déjà un.",
        "Je ne sais pas quel est ton problème, mais je parie que c'est difficile à prononcer.",
        "Le cerveau ne fait pas tout. Dans votre cas, il n'est rien.",
        "En tant qu'étranger, que pensez-vous de la race humaine ?",
        "Tu ressembles à une photo d'avant.",
        "Oh, quoi ? Désolé. J'essayais de t'imaginer avec une personnalité.",
        "C'est grâce à vous que le patrimoine génétique a besoin d'un sauveteur.",
        "Nous pouvons toujours savoir quand vous mentez. Vos lèvres bougent.",
        "J'adore faire du shopping mais je n'achète pas tes conneries.",
        "L'enfer est recouvert de tous vos selfies supprimés.",
        "Vous êtes la preuve vivante que le fumier peut faire germer des pattes et marcher.",
        "Tu réalises que le maquillage ne va pas arranger ta bêtise ?",
        "Te traiter d'idiot serait une insulte à tous les gens stupides.",
        "Tu as le visage parfait pour la radio.",
        "Aww, c'est tellement mignon quand tu essaies de parler de choses que tu ne comprends pas.",
        "Si je voulais avoir des nouvelles d'un connard, je péterais.",
        "Quelle est la différence entre toi et un œuf ? Les œufs sont pondus !",
        "Vous ressemblez à une pierre écrasée dans un tas de sable, roulée en un blunt et fumée avec un inhalateur pour l'asthme.",
        "Vos conseils sont aussi utiles qu'un abri anti-bombes en papier mâché.",
        "Est-ce triste que votre chanson thème puisse aussi bien avoir une signature 0/0 ?",
        "Tu es si gros que tu donnes l'impression que la galaxie est à l'échelle moléculaire.",
    ];

    client.embed({
        title: `😓・Conseil`,
        desc: `${user}, ${roasts[Math.floor(Math.random() * roasts.length)]}`,
        type: 'editreply'
    }, interaction)
}

 